### ISSUE TITLE
http.Server.Serve: "protocol not available" (OpenBSD 6.5)

### ISSUE THREAD

**Issue by peterljung** [aerogo/aero#10] opened 2019-06-02 21:01 UTC
I have problem running the test on OpenBSD 6.5.

```
$ uname -a
OpenBSD nuc.lounge.se 6.5 GENERIC.MP#3 amd64
$ go version
go version go1.12.1 openbsd/amd64
```
This is probably related to something in OpenBSD. I have a very similar issue with another web framework. Could ephemeral port ranges have something to do with it? 

```
$ doas ./aerotest                                                                                                        
Server running on: http://localhost:4000
--------------------------------------------------------------------------------
panic: set tcp 127.0.0.1:4000->127.0.0.1:38930: protocol not available

goroutine 21 [running]:
github.com/aerogo/aero.(*Application).serveHTTP(0xc000102000, 0xc0000a0d88)
	/home/peter/go/pkg/mod/github.com/aerogo/aero@v1.3.7/Application.go:418 +0x29f
created by github.com/aerogo/aero.(*Application).ListenAndServe
	/home/peter/go/pkg/mod/github.com/aerogo/aero@v1.3.7/Application.go:197 +0xe3
```
But maybe you have seen something similar on another platform?

I tried a simple example using `http` on the same machine and that works fine.

```
package main

import (
	"fmt"
	"log"
	"net/http"
)

type helloHandler struct{}

func (h helloHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "hello, you've hit %s\n", r.URL.Path)
}

func main() {
	err := http.ListenAndServe(":9999", helloHandler{})
	log.Fatal(err)
}
```

Any idea what this could be related to?

**Comment by akyoto** [comment] 2019-06-02 23:13
Have never seen this panic before using Arch Linux on [x86_64](https://github.com/akyoto/hardware).

```text
λ uname -a
Linux home 5.1.5-arch1-2-ARCH #1 SMP Mon May 27 03:37:39 UTC 2019 x86_64 GNU/Linux
```

I don't have an OpenBSD installation to test with, but if you're seeing the same problems in another framework then it *might* be something related to your system.

I don't want to be so quick on dropping responsibility onto someone else, though, so let's dig a little deeper.

The line referenced in the panic is this one:

```go
// This will block the calling goroutine until the server shuts down.
// The returned error is never nil and in case of a normal shutdown
// it will be `http.ErrServerClosed`.
err := server.Serve(listener)

if err != http.ErrServerClosed {
	panic(err)
}
```

Via some google searches I found these threads, all returning the same error message:

* https://github.com/coredns/coredns/issues/2239
* https://github.com/golang/go/issues/12598

The message itself is coming from a syscall code 42 on OpenBSD in `go/src/syscall/zerrors_openbsd_amd64.go`:

* https://github.com/golang/go/blob/master/src/syscall/zerrors_openbsd_amd64.go#L1497

This leads me to [searching again](https://www.google.com/?q=openbsd%20error%2042%20protocol%20not%20available) and finding those:

* https://github.com/celery/py-amqp/issues/200
* https://github.com/celery/py-amqp/pull/211
* https://github.com/celery/py-amqp/commit/f812b5695950c713f3f455b8df92336124aa8683

It looks like the problem is related to the `TCP_USER_TIMEOUT` socket option.

**Comment by peterljung** [comment] 2019-06-03 14:41
Yes, you may be on to the problem ...

TCP socket options in linux include `TCP_USER_TIMEOUT`: <http://man7.org/linux/man-pages/man7/tcp.7.html>

    TCP_USER_TIMEOUT (since Linux 2.6.37)

OpenBSD does not: <https://man.openbsd.org/tcp>

Is this a generic problem with the go port or http package? Or can this option be controlled in aero?

I minimal example which trigger the problem would be good to be able to send a bug to OpenBSD mailing lists if it is a general go port problem. I tried with the small HTTP example above but that did not trigger the issue ...

**Comment by peterljung** [comment] 2019-06-03 14:55
gRPC package handles this in: <https://github.com/grpc/grpc-go/blob/master/internal/syscall/syscall_nonlinux.go> vs <https://github.com/grpc/grpc-go/blob/master/internal/syscall/syscall_linux.go>

Is aero dependent on gRPC in some way?

**Comment by akyoto** [comment] 2019-06-03 23:21
Aero doesn't need grpc.

```shell
λ go mod why google.golang.org/grpc
# google.golang.org/grpc
(main module does not need package google.golang.org/grpc)
```

The biggest problem for me in debugging this is not having a physical system to test with. So I thought maybe I'll [download Virtualbox](https://medium.com/@005/openbsd-6-4-installing-a-seriously-underrated-os-in-a-virtual-machine-f5848ee5a25a).

In the meantime, could you try downloading the git repo, using the repo via [replace](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) and removing the following lines from the source:

1. https://github.com/aerogo/aero/blob/v1.3.10/Application.go#L378-L380
1. https://github.com/aerogo/aero/blob/v1.3.10/Listener.go#L24-L36

Only remove the second if the first didn't work. If removing the timeouts from the first link works, I'm honestly going to be surprised. These timeouts are important and exist for a reason. Without these timeouts, you will have a lot of idle connections and your app will eventually crash. This *might* be circumvented by putting something like `nginx` in front of the server, but if the server is the main server / actual endpoint of the client then you definitely would want to have these timeouts.

**Comment by akyoto** [comment] 2019-06-04 03:47
Found the culprit, it's https://github.com/aerogo/aero/blob/v1.3.11/Listener.go#L32

```go
connection.SetKeepAlivePeriod(keepAlivePeriod)
```

![Aero on OpenBSD](https://i.imgur.com/15nND2Z.png)

**Comment by akyoto** [comment] 2019-06-04 03:56
Fixed in [1.3.12](https://github.com/aerogo/aero/releases/tag/v1.3.12) via https://github.com/aerogo/aero/commit/079571728d466eb915cc2d9d596a20aa45bdb341:

![Aero 1.3.12 on OpenBSD](https://i.imgur.com/DRLAQFg.png)

**Closed by akyoto** 2019-06-04 03:56 UTC
Labels: unclear

**Comment by peterljung** [comment] 2019-06-04 06:58
Super thanks!

I suppose you need to handle timeouts in the application code to avoid triggering the TCP timeout.

**Comment by akyoto** [comment] 2019-06-05 00:15
I might be wrong, but I believe there is a default TCP timeout considering that `SetKeepAlive(true)` is returning no errors on OpenBSD.
